initial version
parrot-com/cookiecutter-python pull request #1
Opened 2022-07-31 20:36 UTC by jerguslejko

this is the initial version of our `cookiecutter-python` template. there are a few things left out, which we can add after merge (see TODO in readme)

2022-08-01 13:54 UTC, vlktomas approved these changes
lgtm

2022-08-01 13:54 UTC, vlktomas commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}
what's `${{ "{{" }}`? it's because of cookiecutter

2022-08-01 13:58 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}
yeah because of cookiecutter :/ I didn't find a better way to do this. you can exclude entire files from being interpolated, but we need to interpolate some stuff here

2022-08-01 15:15 UTC, lachtanek commented on {{ cookiecutter.app_name }}/pyproject.toml
> +flake8 = "^4.0.1"
we should also add `flake8-bugbear`, since we have it also in `pre-commit`, or remove it from `pre-commit`

2022-08-01 15:15 UTC, lachtanek commented on {{ cookiecutter.app_name }}/.flake8
> +exclude = .git,__pycache__,.pytest_cache
we could maybe try https://pypi.org/project/Flake8-pyproject/ instead of this, but we can also do this as a follow-up

2022-08-01 15:15 UTC, lachtanek commented on {{ cookiecutter.app_name }}/.flake8
> +max-line-length = 120
I propose holding `black`'s 88 line length for new projects, wdyt?

2022-08-01 15:15 UTC, lachtanek commented on {{ cookiecutter.app_name }}/tests/conftest.py
> +        setattr(settings, override, original[override])
wdyt about extracting this to some library?

2022-08-02 09:40 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/pyproject.toml
> +flake8 = "^4.0.1"
added

2022-08-02 09:40 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/pyproject.toml
> +flake8 = "^4.0.1"
I also removed `poetry.lock` which shouldn't be in the template

2022-08-02 09:40 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/.flake8
> +exclude = .git,__pycache__,.pytest_cache
added as follow up

2022-08-02 09:41 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/.flake8
> +max-line-length = 120
I don't mind long lines tbh... my screen is wide :D 120 works well imho

2022-08-02 09:41 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/Dockerfile
> +RUN pip install /app
this is added as a followup

2022-08-02 09:42 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/tests/conftest.py
> +        setattr(settings, override, original[override])
`parrottools.testing` 👍 

added as followup

2022-08-02 11:42 UTC, mrknmc commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}
we could try using the GHA cache instead: https://github.com/parrot-com/parrot/pull/3707/files

2022-08-02 11:42 UTC, mrknmc commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          aws-region: us-east-1
this shouldn't be necessary in CI

2022-08-02 11:43 UTC, mrknmc commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +            poetry run isort --check .
nit idea: we could run flake8, black, mypy and isort in parallel in a separate job or workflow even

2022-08-02 11:44 UTC, mrknmc commented on {{ cookiecutter.app_name }}/Dockerfile
> +RUN pip install /app
I agree with @lachtanek  - we shouldn't install apps into the system

2022-08-02 11:45 UTC, mrknmc commented on {{ cookiecutter.app_name }}/Dockerfile
> +	&& pip install --no-cache-dir "poetry==$POETRY_VERSION" \
I'm sure we already talked about this but this is not recommended: https://python-poetry.org/docs/#installing-with-pip

we can do it in a followup but then there will be two things you need to fix

2022-08-02 11:46 UTC, mrknmc commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}
just saw the readme...

2022-08-02 11:46 UTC, mrknmc commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +            poetry run isort --check .
just saw the readme...

2022-08-02 11:47 UTC, mrknmc approved these changes
overall lgtm, RE followup - I just hope we get around to it

2022-08-03 12:49 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/tests/conftest.py
> +        setattr(settings, override, original[override])
actually, this depends on the `Settings` class which inherits from pydantic ... we might need to keep it here

2022-08-03 12:51 UTC, vetyy commented on {{ cookiecutter.app_name }}/README.md
> +    * add `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the "Settings -> Secrets -> Actions"
This is not needed anymore

2022-08-03 12:53 UTC, vetyy commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +    log_level: Literal["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"] = "ERROR"
btw I never used CRITICAL in any project

2022-08-03 12:56 UTC, vetyy commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/main.py
> +from {{ cookiecutter.app_name }}.metrics import TICKS
I was just thinking if we don't want to do something like `src` or `app` folder where the code is, so you can avoid doing this kind of templating to imports

2022-08-03 12:58 UTC, vetyy commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +class Settings(BaseSettings):
To avoid constantly loading .env file
```suggestion
@functools.lru_cache
class Settings(BaseSettings):
```

2022-08-03 12:59 UTC, vetyy commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +    prometheus_port: int = 8081
and then have `if settings.prometheus_enabled` around starting HTTP server, to avoid starting it during tests or w/e
```suggestion
    prometheus_enabled: bool = True
    prometheus_port: int = 8081
```

2022-08-03 13:01 UTC, vetyy approved these changes

2022-08-04 16:16 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/Dockerfile
> +	&& pip install --no-cache-dir "poetry==$POETRY_VERSION" \
I redid it and installed using `apk` (I switched the base to alpine) which doesn't install it in the system namespace

2022-08-04 16:16 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/Dockerfile
> +RUN pip install /app
removed this step

2022-08-04 16:17 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/main.py
> +from {{ cookiecutter.app_name }}.metrics import TICKS
we had `src` module in `reporters` but we renamed it to `reporters` based on @mrknmc suggestion

2022-08-04 16:37 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +class Settings(BaseSettings):
added

2022-08-04 16:37 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +    log_level: Literal["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"] = "ERROR"
removed

2022-08-04 16:38 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/README.md
> +    * add `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the "Settings -> Secrets -> Actions"
removed

2022-08-04 16:38 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +    prometheus_port: int = 8081
added

2022-08-05 15:16 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/pyproject.toml
> +flake8 = "^4.0.1"
weell I added `poetry.lock` back bc it creates a weird dynamic where you render a new project and can't run `docker build` bc it fails on copying non-existing `poetry.lock` while `poetry` lives inside the container...

2022-08-08 14:50 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}
used

2022-08-08 14:50 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/.github/workflows/main.yaml
> +          aws-region: us-east-1
unfortunately it is required for the gh action to run

2022-08-08 15:01 UTC, lachtanek requested changes
plz see my comment about lru_cache settings, outside of that LGTM

2022-08-08 15:01 UTC, lachtanek commented on {{ cookiecutter.app_name }}/Dockerfile
> +RUN poetry install --no-dev
why do we need to install scripts in prod container?

2022-08-08 15:04 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/Dockerfile
> +RUN poetry install --no-dev
so we the entry point can be just `CMD ["{{ cookiecutter.app_name }}"]`

2022-08-08 15:12 UTC, jerguslejko commented on {{ cookiecutter.app_name }}/{{ cookiecutter.app_name }}/config.py
> +class Settings(BaseSettings):
okay, we can add later if needed

2022-08-08 15:15 UTC, merged